services:
  api:
    build: ./backend
    container_name: oneMarket_api
    env_file: .env
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/api
      - /usr/src/api/node_modules
    command: sh -c "npm install && npm run dev"
    environment:
      DATABASE_URL: "postgres://${DB_USERNAME}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}"
    networks:
      - app-network

  app:
    build: ./frontend/
    container_name: oneMarket_app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - api
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run dev"
    environment:
      API_URL: "${API_URL}"
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: oneMarket_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
